stages:
  data_processing:
    cmd: python -m src.stages.data_processing -c "params.yaml"
    deps:
    - src/stages/data_processing.py
    - data/raw/train.csv
    - data/raw/test.csv
    - data/raw/sample_submission.csv
    params:
    - base
    - data_processing
    outs:
    - data/processed/train_x_processed.pt
    - data/processed/train_y_processed.pt
    - data/processed/valid_x_processed.pt
    - data/processed/valid_y_processed.pt
    - data/processed/test_processed.pt

  train:
    cmd: python -m src.stages.train -c "params.yaml"
    deps:
    - src/stages/train.py
    - data/processed/train_x_processed.pt
    - data/processed/train_y_processed.pt
    - data/processed/valid_x_processed.pt
    - data/processed/valid_y_processed.pt
    params:
    - base
    - train
    outs:
    - models/model.pth
    - models/optimizer.pth

  eval:
    cmd: python -m src.stages.eval -c "params.yaml"
    deps:
    - src/stages/eval.py
    - models/model.pth
    params:
    - train
    - eval
    metrics:
    - metrics.json:
        cache: false
