stages:
  data_processing:
    cmd: python -m src.stages.data_processing -c "params.yaml"
    deps:
    - src/stages/data_processing.py
    - data/raw/train.csv
    - data/raw/test.csv
    - data/raw/sample_submission.csv
    params:
    - base
    - data_processing
    outs:
    - data/processed/train_x_processed.pt
    - data/processed/train_y_processed.pt
    - data/processed/valid_x_processed.pt
    - data/processed/valid_y_processed.pt
    - data/processed/test_processed.pt

  train:
    cmd: python -m src.stages.train -c "params.yaml"
    deps:
    - src/stages/train.py
    - data/processed/train_x_processed.pt
    - data/processed/train_y_processed.pt
    - data/processed/valid_x_processed.pt
    - data/processed/valid_y_processed.pt
    params:
    - base
    - train
    plots:
    - reports/results.csv:
        x: epoch
        y: accuracy
        title: Accuracy over Epochs
        x_label: Epoch
        y_label: Accuracy
    - reports/results.csv:
        x: epoch
        y: loss
        title: Loss over Epochs
        x_label: Epoch
        y_label: Loss
    outs:
    - models/model.pth
    - models/optimizer.pth

  eval:
    cmd: python -m src.stages.eval -c "params.yaml"
    deps:
    - data/processed/valid_x_processed.pt
    - data/processed/valid_y_processed.pt
    - src/stages/eval.py
    - models/model.pth
    params:
    - train
    - eval
    metrics:
    - metrics.json:
        cache: false

  submission:
    cmd: python -m src.stages.submission -c "params.yaml"
    deps:
    - data/processed/test_processed.pt
    - src/stages/submission.py
    - models/model.pth
    outs:
    - reports/submission.csv
