base:
  project: digit_recognisation
  raw_data_dir: data/raw/
  processed_data_dir: data/processed/
  random_seed: 13
  device: mps

data_processing:
  split: 0.01

train:
  cudnn_enabled: false
  model_path: models/model.pth
  optimizer_path: models/optimizer.pth
  data:
    batch_size_train: 100
    batch_size_validation: 1000
    shuffle: true
  struct:
    conv1: 16
    conv2: 32
    linear1: 10
  optimizer:
    type: sgd
    learning_rate: 0.01
    momentum: 0.9
  n_epochs: 100
  log_interval: 10

eval:
  metrics_path: metrics.json
