base:
  project: digit_recognisation
  raw_data_dir: data/raw/
  processed_data_dir: data/processed/
  random_seed: 13

data_processing:
  split: 0.3

train:
  cudnn_enabled: False
  model_path: models/models.pth
  optimizer_path: models/optimizer.pth
  data:
    batch_size_train: 64
    batch_size_validation: 100
    shuffle: True
  struct:
    conv1: 10
    conv2: 20
    linear1: 50
    linear2: 10
  learning_rate: 0.001
  momentum: 0.5
  n_epochs: 100
  log_interval: 10




